name = "Elysian Meadows"
author = "LumeaDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66976bf5ba1a9809b88342e4f747a426f88572070328232f22318f2a2d7a6604"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
