name = "Elysian Meadows"
author = "LumeaDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0e8164801e344f1305a30bcb7d11207d38d5909bc033b97485e34c79169f6dd"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
