name = "Elysian Meadows"
author = "LumeaDev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beeba2dc0fde0702e20a1d6285983f14ad0f12b624bf01376f64666a22fd5a42"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
